version: "3"
services:
  pialert:
    container_name: network-device-monitor
    hostname: PiAlert
    privileged: true
    image: jokobsk/pi.alert:latest
    environment:
      - TZ=Europe/Amsterdam
    restart: always
    volumes:
      - ./pialert/pialert_db:/home/pi/pialert/db
      - ./pialert/pialert_config:/home/pi/pialert/config
    network_mode: host
