services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: "1G"
      MEMORY: "4G"
      MAX_MEMORY: "6G"
      DIFFICULTY: "normal"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      MAX_BUILD_HEIGHT: "500"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "0"
      MODE: "survival"
      PVP: "false"
      LEVEL_TYPE: "normal"
      ONLINE_MODE: "true"
      ALLOW_FLIGHT: "true"
      SERVER_NAME: "Berenbenis"

      TYPE: "FORGE"
      VERSION: "1.20.1"
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: |
        https://www.curseforge.com/minecraft/mc-mods/dynmapforge
        https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap
        https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map
        https://www.curseforge.com/minecraft/mc-mods/xaeroplus
        https://www.curseforge.com/minecraft/mc-mods/jei
        https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep
        https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer
        https://www.curseforge.com/minecraft/mc-mods/rpg-hud
        https://www.curseforge.com/minecraft/mc-mods/chat-heads
        https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions
        https://www.curseforge.com/minecraft/mc-mods/food-effect-tooltips-forge
        https://www.curseforge.com/minecraft/mc-mods/effect-tooltips
        https://www.curseforge.com/minecraft/mc-mods/inventory-sorter

        https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered
        https://www.curseforge.com/minecraft/mc-mods/ambientsounds
        https://www.curseforge.com/minecraft/mc-mods/waterdripsound
        https://www.curseforge.com/minecraft/mc-mods/projectile-sounds

        https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod
        https://www.curseforge.com/minecraft/mc-mods/tree-harvester
        https://www.curseforge.com/minecraft/mc-mods/better-animations-collection
        https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay
        https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge

        https://www.curseforge.com/minecraft/mc-mods/cobblegenrandomizer
        https://www.curseforge.com/minecraft/mc-mods/corpse
        https://www.curseforge.com/minecraft/mc-mods/netherportalfix
        https://www.curseforge.com/minecraft/mc-mods/guard-villagers
        https://www.curseforge.com/minecraft/mc-mods/lootr

        https://www.curseforge.com/minecraft/mc-mods/modernfix
        https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save
        https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric
        https://www.curseforge.com/minecraft/mc-mods/connectivity
        https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak
        https://www.curseforge.com/minecraft/mc-mods/leaky

        https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

        https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island
        https://www.curseforge.com/minecraft/mc-mods/yungs-bridges
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts
        https://www.curseforge.com/minecraft/mc-mods/yungs-extras
        https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples
        https://www.curseforge.com/minecraft/mc-mods/better-village-forge
        https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
        https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise
        https://www.curseforge.com/minecraft/mc-mods/horror-elements-mod

        https://www.curseforge.com/minecraft/mc-mods/collective
        https://www.curseforge.com/minecraft/mc-mods/yungs-api
        https://www.curseforge.com/minecraft/mc-mods/cupboard
        https://www.curseforge.com/minecraft/mc-mods/citadel
        https://www.curseforge.com/minecraft/mc-mods/puzzles-lib
        https://www.curseforge.com/minecraft/mc-mods/balm
        https://www.curseforge.com/minecraft/mc-mods/terrablender
        https://www.curseforge.com/minecraft/mc-mods/creativecore
        https://www.curseforge.com/minecraft/mc-mods/cloth-config
        https://www.curseforge.com/minecraft/mc-mods/bookshelf
        https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption
        https://www.curseforge.com/minecraft/mc-mods/jade
        https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge

    volumes:
      - ${DATA_DIRECTORY}:/data
